server:
  port: 80
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
      active: druid
#mybatis:
#  mapper-locations:
#   # 搜索指定包别名
#  type-aliases-package: com.ctc.myspringboot.dao
#  configLocation: classpath:mybatis/mybatis-config.

mybatis-plus:
  mapper-locations: classpath:mybatis/*/*.xml
  configuration: classpath:mybatis/mybatis-config.xml

